// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Auht struct {
	ID       string `json:"id"`
	RefToken string `json:"refToken"`
	UserID   string `json:"userId"`
}

type AuthResponse struct {
	AuthTokens *AuthTokens `json:"authTokens"`
	User       *User       `json:"user"`
}

type AuthTokens struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiredAt    time.Time `json:"expiredAt"`
	UserID       string    `json:"userId"`
}

type Message struct {
	Message string `json:"message"`
}

type Refresh struct {
	RefreshToken string `json:"refreshToken"`
}

type SignInUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUpUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
