// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"twoBinPJ/domains/user"
)

type AuthResponse struct {
	AuthTokens *user.AuthTokens `json:"authTokens"`
	User       *user.User       `json:"user"`
}

type Message struct {
	Message string `json:"message"`
}

type Refresh struct {
	RefreshToken string `json:"refreshToken"`
}

type SignInUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUpUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
