Webport1: "8084"
Webport2: "8085"
DataBaseHost: "localhost"
DataBasePort: "5432"
DataBaseUsername: "postgres "
DataBaseDbname: "graphQLDB"
DataBaseSslmode: "disable"
DataBasePassword: "1234"
AtExpires: "9000000000000"
RtExpires: "86400000000000"
